config/routes.rb
Rails.application.routes.draw do
  resources :todo_records
  resources :books
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "todo_records#index"

  get 'todo_dashboard', to: 'todo_records#index', as: 'tai'
  get 'todo_show/:id', :to => 'todo_records#show'
  get 'todo_edit/:id', :to => 'todo_records#edit'
  get 'todo_update/:id', :to => 'todo_records#update'
  get 'todo_delete/:id', :to => 'todo_records#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book_record.rb
class BookRecord < ApplicationRecord
end

app/models/practise.rb
class PractiseController < ApplicationRecord
end

app/models/todo_record.rb
class TodoRecord < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/book_records_controller.rb
class BookRecordsController < ApplicationController
  before_action :set_book_record, only: %i[ show edit update destroy ]

  def index
    @book_record = BookRecord.all
  end

  # GET /book_records/1 or /book_records/1.json
  def show
  end

  # GET /book_records/new
  def new
    @book_record = BookRecord.new
  end

  # GET /book_records/1/edit
  def edit
  end

   # POST /book_records or /book_record.json
  def create
    @book_record = BookRecord.new(todo_list_params)

    respond_to do |format|
      if @book_record.save
        format.html { redirect_to book_record_url(@book_record), notice: "Todo list was successfully created." }
        format.json { render :show, status: :created, location: @book_record }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book_record.errors, status: :unprocessable_entity }
      end
    end
  end


def update
  @book = Book.find(params[:id])
  if @book.update(book_params)
    redirect_to(@book)
  else
    render "edit"
  end
end



end

app/controllers/practise_controller.rb
class PractiseController < ApplicationController
end

app/controllers/todo_records_controller.rb
class TodoRecordsController < ApplicationController
  before_action :set_todo_record, only: %i[ show edit update destroy ]

  # GET /todo_records or /todo_records.json
  def index
    @todo_records = TodoRecord.all

  end

  # GET /todo_records/1 or /todo_records/1.json
  def show
  end

  # GET /todo_records/new
  def new
    @todo_record = TodoRecord.new
  end

  # GET /todo_records/1/edit
  def edit
  end

  # POST /todo_records or /todo_records.json
  def create
    @todo_record = TodoRecord.new(todo_record_params)

    respond_to do |format|
      if @todo_record.save
        format.html { redirect_to todo_record_url(@todo_record), notice: "Todo record was successfully created." }
        format.json { render :show, status: :created, location: @todo_record }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @todo_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todo_records/1 or /todo_records/1.json
  def update
    respond_to do |format|
      if @todo_record.update(todo_record_params)
        format.html { redirect_to todo_record_url(@todo_record), notice: "Todo record was successfully updated." }
        format.json { render :show, status: :ok, location: @todo_record }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @todo_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todo_records/1 or /todo_records/1.json
  def destroy
    @todo_record.destroy

    respond_to do |format|
      format.html { redirect_to todo_records_url, notice: "Todo record was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo_record
      @todo_record = TodoRecord.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def todo_record_params
      params.require(:todo_record).permit(:title, :description, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/practise_helper.rb
module PractiseHelper
end

app/helpers/todo_records_helper.rb
module TodoRecordsHelper
end

app/views/book_records/index.html.erb
<h1>Listing Books</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.content %></td>
        <td><%= link_to "Show", book %></td>
        <td><%= link_to "Edit", edit_book_path(book) %></td>
        <td><%= link_to "Destroy", book, data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to "New book", new_book_path %>

app/views/layouts/application.html.erb
<%= stylesheet_link_tag    "application" %>
<%= javascript_include_tag "application" %>

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

<style>
.gradient-custom {
  background: radial-gradient(50% 123.47% at 50% 50%, #00ff94 0%, #720059 100%),
    linear-gradient(121.28deg, #669600 0%, #ff0000 100%),
    linear-gradient(360deg, #0029ff 0%, #8fff00 100%),
    radial-gradient(100% 164.72% at 100% 100%, #6100ff 0%, #00ff57 100%),
    radial-gradient(100% 148.07% at 0% 0%, #fff500 0%, #51d500 100%);
  background-blend-mode: screen, color-dodge, overlay, difference, normal;
}
</style>

  <body>
    <section class="gradient-custom">
      <div class="container py-5" >
    <%= yield %>

      </div>
</section>
  </body>
</html>

app/views/todo_records/_form.html.erb
<%= form_with(model: todo_record) do |form| %>
  <% if todo_record.errors.any? %>
  <div style="color: red">
      <h2><%= pluralize(todo_record.errors.count, "error") %> prohibited this todo_record from being saved:</h2>

      <ul>
        <% todo_record.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
    <form >
      <div class="mb-3">
        <%= form.label :title, style: "display: block" %>
        <%= form.text_field :title, class: "form-control"  %>
      </div>
      <div class="mb-3">
        <%= form.label :description, class:"form-label", style: "display: block" %>
        <%= form.text_area :description, class: "form-control",id:"todo_descid"  %>
      </div>
      <div class="mb-3">
         <label for="tod_status" class="form-label">Status</label>
        <%= form.select(:status, ['Draft','In Active', 'Cancelled','Completed'], {include_blank: ""}, { :class => 'form-select form',required:true }) %>
      </div>

      <button type="submit" class="btn btn-success">Submit</button>
      <%= link_to "ToDo Lists", todo_records_path, class:'btn btn-primary' %>
    </form>
    <% end %>

app/views/todo_records/_todo_record.html.erb
<div id="<%= dom_id todo_record %>">
      <div class="mb-3">
        <label for="exampleFormControlInput1" class="form-label">Title</label>
        <input type="text" class="form-control"   value="<%= todo_record.title %>" disabled> 
      </div>
       <div class="mb-3">
        <label for="exampleFormControlInput1" class="form-label">Description</label>
        <input type="text" class="form-control"   value="<%= todo_record.description %>" disabled> 
      </div>
      <div class="mb-3">
        <label for="exampleFormControlInput1" class="form-label">Status</label>
        <input type="text" class="form-control"  value="<%= todo_record.status %>" disabled> 
      </div>

</div>

app/views/todo_records/edit.html.erb
<h1>Editing todo record</h1>

<%= render "form", todo_record: @todo_record %>

<br>

app/views/todo_records/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Todo Lists</h1>

    <div id="todo_records">
      <div class="tab-content" id="ex1-content">
        <% @todo_records.each do |todo_record| %>
          <%= link_to [todo_record] do %>
          <div class="tab-pane fade show active" id="ex1-tabs-1" role="tabpanel" aria-labelledby="ex1-tab-1" onclick="">
            <ul class="list-group mb-0">
              <li class="list-group-item d-flex align-items-center border-0 mb-2 rounded"
                        style="background-color: #f4f6f7;">

                <input class="form-check-input me-2" type="checkbox" value="" aria-label="..." />
                        <%= todo_record.title %>
              </li>
            </ul>
          </div>
           <% end %>
        <% end %>
      </div>
    </div>

      <%= link_to "New ToDo Item ", new_todo_record_path, class: 'btn btn-success ms-2' %>


 

app/views/todo_records/new.html.erb
<h1>New ToDo Item</h1>

    <%= render "form", todo_record: @todo_record %>

app/views/todo_records/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @todo_record %>
<div>

   <%= link_to "Edit this todo item ", edit_todo_record_path, class: 'btn btn-success ms-2' %>

   <%= link_to "Back to Todo Lists ", todo_records_path, class: 'btn btn-info ms-2' %>

   <%= button_to "Delete this item ", @todo_record, method: :delete, class: 'btn btn-danger ms-2' %>
</div>